# Generated by Django 4.2.13 on 2024-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0001_initial'),
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='categoryApp.category'),
        ),
    ]
